/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/banners': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get all banners */
    get: operations['getBanners'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/request-otp': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Запрос одноразового кода подтверждения
     * @description Создаёт и отправляет OTP пользователю.
     */
    post: operations['requestOtp'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/verify-otp': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Подтверждение одноразового кода
     * @description Проверяет OTP и возвращает пару токенов.
     */
    post: operations['verifyOtp'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Обновление токенов авторизации
     * @description Обновляет токены по refresh-cookie или заголовку.
     */
    get: operations['refresh'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Получение текущего пользователя
     * @description Возвращает профиль текущего пользователя.
     */
    get: operations['getMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/complete-profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Дополнение профиля пользователя
     * @description Обновляет профиль после первичного входа.
     */
    post: operations['completeProfile'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/media/avatar/upload-request': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Получение presigned URL для загрузки аватара
     * @description Возвращает presigned URL и идентификатор медиа-объекта для аватара пользователя.
     */
    post: operations['avatarUploadRequest'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/media/avatar/preview-upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Получение preview URL для загрузки аватара
     * @description Возвращает preview URL для загрузки аватара.
     */
    post: operations['avatarPreviewUpload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    DateRange: {
      /** Format: date-time */
      from?: string;
      /** Format: date-time */
      to?: string;
    };
    Pagination: {
      after?: string;
      before?: string;
      first?: number;
      last?: number;
    };
    /** @enum {string} */
    SortDirection: SortDirection;
    Sort: {
      direction?: components['schemas']['SortDirection'];
      field?: string;
    };
    BannerFile: {
      /** Format: uuid */
      id: string;
      /** Format: uri */
      url: string;
    };
    Banner: {
      /** Format: date-time */
      createdAt: string;
      /** Format: uuid */
      id: string;
      isNew: boolean;
      logo: components['schemas']['BannerFile'];
      opacity: number;
      sequence: number;
      subtitle?: string | null;
      title?: string | null;
      url?: string | null;
    };
    BannerEdge: {
      cursor?: string | null;
      node: components['schemas']['Banner'];
    };
    PageInfo: {
      endCursor?: string | null;
      hasNextPage: boolean;
      hasPreviousPage: boolean;
      startCursor?: string | null;
    };
    Error: {
      statusCode: number;
      message: string;
      error?: string;
    };
    ThrottledErrorResponse: {
      /** @enum {string} */
      code: ThrottledErrorResponseCode;
      message?: string;
      /** @description Рекомендованная задержка перед повторной попыткой */
      retryAfterSec: number;
    };
    ErrorResponse: {
      /** @description Код ошибки для обработки на клиенте */
      code: string;
      /** @description Человекочитаемое описание ошибки */
      message?: string;
      /** @description Дополнительные детали ошибки */
      details?: {
        [key: string]: unknown;
      };
    };
    TokenPair: {
      /** @description JWT access-токен */
      accessToken: string;
      /** @description JWT refresh-токен */
      refreshToken: string;
    };
    Avatar: {
      /** Format: uri */
      largeUrl: string;
      /** Format: uri */
      mediumUrl: string;
      /** Format: uri */
      smallUrl: string;
      /** Format: uri */
      thumbUrl: string;
    };
    User: {
      /**
       * Format: uuid
       * @description Уникальный идентификатор пользователя
       */
      id: string;
      /** @description Телефон в формате E.164 */
      phoneNumber: string;
      fullName?: string;
      avatar?: components['schemas']['Avatar'];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /** @enum {string} */
    MediaVisibility: MediaVisibility;
    LinkMediaData: {
      bucket: string;
      objectKey: string;
      /** @description Идентификатор загруженного медиа-объекта */
      mediaId: string;
      visibility: components['schemas']['MediaVisibility'];
      contentType?: string;
    };
    GetMediaUploadUrlInput: {
      contentType?: string;
    };
    GetMediaUploadUrlResult: {
      bucket: string;
      objectKey: string;
      mediaId: string;
      visibility: components['schemas']['MediaVisibility'];
      contentType?: string;
      /** Format: uri */
      url: string;
    };
  };
  responses: {
    /** @description Resource not found */
    NotFoundError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getBanners: {
    parameters: {
      query?: {
        filter?: {
          createdAt?: components['schemas']['DateRange'];
        };
        pagination?: components['schemas']['Pagination'];
        sort?: components['schemas']['Sort'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of banners */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            edges: components['schemas']['BannerEdge'][];
            pageInfo: components['schemas']['PageInfo'];
            totalCount: number;
          };
        };
      };
      404: components['responses']['NotFoundError'];
    };
  };
  requestOtp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description Телефон в формате E.164 */
          phoneNumber: string;
          /**
           * @description Канал доставки OTP
           * @enum {string}
           */
          channel?: PathsAuthRequestOtpPostRequestBodyApplicationJsonChannel;
          /** @description Локаль для текстов уведомлений */
          locale?: string;
        };
      };
    };
    responses: {
      /** @description OTP отправлен */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description Рекомендованная задержка до следующего запроса OTP */
            nextRetrySec?: number;
          };
        };
      };
      /** @description Слишком много запросов */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ThrottledErrorResponse'];
        };
      };
    };
  };
  verifyOtp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description Телефон в формате E.164 */
          phoneNumber: string;
          /** @description Код подтверждения из SMS */
          code: string;
        };
      };
    };
    responses: {
      /** @description Авторизация успешна */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description JWT access-токен */
            accessToken: string;
            /** @description JWT refresh-токен */
            refreshToken: string;
            /** @description Признак необходимости дозаполнить профиль */
            needProfile: boolean;
          };
        };
      };
      /** @description Некорректный запрос */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Превышено количество попыток */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            code: PathsAuthVerifyOtpPostResponses403ContentApplicationJsonCode;
            message?: string;
            retryAfterSec?: number;
          };
        };
      };
      /** @description Слишком много запросов */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ThrottledErrorResponse'];
        };
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header: {
        'x-refresh-token': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Токены обновлены */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenPair'];
        };
      };
      /** @description Невалидный refresh-токен */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Профиль пользователя */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  completeProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          fullName?: string;
          avatarMedia?: components['schemas']['LinkMediaData'];
        };
      };
    };
    responses: {
      /** @description Обновлённый профиль */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      /** @description Некорректный запрос */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  avatarUploadRequest: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GetMediaUploadUrlInput'];
      };
    };
    responses: {
      /** @description Presigned URL для загрузки */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GetMediaUploadUrlResult'];
        };
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  avatarPreviewUpload: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LinkMediaData'];
      };
    };
    responses: {
      /** @description URL превью аватара */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Avatar'];
        };
      };
      /** @description Не авторизован */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
}
export enum PathsAuthRequestOtpPostRequestBodyApplicationJsonChannel {
  sms = 'sms',
  whatsapp = 'whatsapp',
}
export enum PathsAuthVerifyOtpPostResponses403ContentApplicationJsonCode {
  otp_attempts_exceeded = 'otp_attempts_exceeded',
}
export enum SortDirection {
  ASC = 'ASC',
  DESC = 'DESC',
}
export enum ThrottledErrorResponseCode {
  throttled = 'throttled',
}
export enum MediaVisibility {
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE',
}
